/*
 * File: app/store/NewsFeed.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CON.store.NewsFeed', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json',
        'Ext.data.Field'
    ],

    config: {
        autoLoad: true,
        storeId: 'NewsFeed',
        proxy: {
            type: 'jsonp',
            timeout: 90000,
            url: 'http://aceconapi.walkingtree.in/server/server.php',
            reader: {
                type: 'json',
                rootProperty: 'channel.item'
            }
        },
        fields: [
            {
                name: 'title'
            },
            {
                name: 'description'
            },
            {
                name: 'link'
            },
            {
                name: 'pubDate'
            },
            {
                name: 'guid'
            }
        ],
        listeners: [
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            },
            {
                fn: 'onJsonpstoreBeforeLoad',
                event: 'beforeload'
            }
        ]
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {

    },

    onJsonpstoreBeforeLoad: function(store, operation, eOpts) {

    }

});