/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    paths: {
        'WTC.ux': 'wtc/ux'
    }
});


Ext.application({

    requires: [
        'Ext.Loader',
        'WTC.ux.Cover'
    ],
    title: 'Cup of News',
    models: [
        'Publication',
        'Category',
        'Dictionary',
        'CategoryList',
        'PublicationList',
        'CategoryPublications',
        'Words',
        'TopView',
        'localData'
    ],
    stores: [
        'NewsFeed',
        'Category',
        'Publication',
        'Dictonary',
        'CategoryList',
        'PublicationList',
        'CategoryPublications',
        'publication1',
        'Words',
        'TopView',
        'TopViewsList',
        'localData'
    ],
    views: [
        'category.ListCover',
        'publication.List',
        'publication.CatNewsList',
        'publication.Detail',
        'MainNav',
        'HomeScreen',
        'MyPanel',
        'PublicationPref',
        'category.PubNewsList',
        'MyMenu',
        'MyDictionaryList',
        'Dictionarydetail',
        'SelectPublication',
        'Toprated',
        'topViewList',
        'PopUp'
    ],
    controllers: [
        'Publication',
        'Main',
        'Category',
        'TopNews'
    ],
    name: 'CON',

    launch: function() {
        Ext.fly('appLoadingIndicator').destroy();
        /*
        document.addEventListener("deviceready", function(){
            alert("device ready");

        document.addEventListener("online", function(){alert("online");}, false);
        document.addEventListener("offline", function(){alert("offline");}, false);




                                                           }, false);

        */
        Ext.create('CON.view.MainNav', {fullscreen: true});
    },

    deleteDictionary: function(id) {



            var jsondata=[];

            Ext.getStore('Dictonary').each(function(record) {

            if (record.get('id') === id) {
                Ext.getStore('Dictonary').remove(record);
            }else{
                jsondata.push({"id":record.get("id"),"word":record.get("word")});
            }
            }, this);


              //  window.localStorage.setItem("DictionaryArray",JSON.stringify(jsondata));



    },

    playMusic: function() {


            var audioLink=CON.utils.Global.currentAudiolink;
            var audio=new Audio();
            audio.src=audioLink;
            audio.play();



    },

    openAdmobSite: function() {
        window.open("http://walkingtree.in/");
    }

});
