/*
 * File: app/view/category/ListCover.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CON.view.category.ListCover', {
    extend: 'Ext.Container',
    alias: 'widget.categorycover',

    config: {
        centered: true,
        layout: 'vbox'
    },

    initialize: function() {
        this.callParent();
        var CategoryList = Ext.getStore('CategoryList');

        var cover = Ext.create('WTC.ux.Cover', {
        			itemCls: 'my-cover-item',
            height:'100%',
        			//height: (Ext.os.deviceType !== 'Phone')? 300: undefined,
                    //	width: (Ext.os.deviceType !== 'Phone')? 800: undefined,
                    width:'100%',
        			itemTpl : [
        				'<div>',

        					'<div class="company">{name}</div>',
        					'<div class="image"><tpl if="image"><img  src="{image}"></tpl></div>',
        				'</div>'
        			],
                    store:CategoryList,
                    selectedIndex: 5,
        			listeners:{
        				itemdoubletap: function(){
        					console.log('itemdbltap', arguments);
        				},
        				itemtap: function(cover, idx){

                           CON.app.fireEvent('catItemTapped', cover, idx);
        				},
        				scope: this
        			}
        		});

            this.add(cover);
    }

});