/*
 * File: app/controller/Category.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CON.controller.Category', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            publicationsegbtns: 'segmentedbutton#publicationsegbtns',
            categoryPubNewsList: 'list#pubnewslist'
        },

        control: {
            "segmentedbutton#publicationsegbtns": {
                toggle: 'onSegmentedbuttonToggle'
            },
            "list#pubnewslist": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onSegmentedbuttonToggle: function(segmentedbutton, button, isPressed, eOpts) {
        if(isPressed){

          //Ext.Viewport.setMasked({xtype:'loadmask',message:'your custom loadmask'});
        var category=(button.config.pubCategData);
             CON.utils.Global.api.currentPubid=parseInt(category.publicationId );
                   CON.utils.Global.api.currentCatid=parseInt(category.categoryId );

         var feedUrl = button.config.pubCategData.feedurl;
         this.feedStore = Ext.create('CON.store.NewsFeed');

        	this.feedStore.setParams({'feedurl':feedUrl});
            button.up('list').setStore(this.feedStore);
        	this.feedStore.load({
        		callback:function(records){

        		},
                scope: this
        	});

        }

    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
        var alldat=(record.getData());
        Ext.data.JsonP.request({

                    url: 'http://aceconapi.walkingtree.in/toprest/trackviews',
                    params: {
                        title : alldat.title ,
                        link:alldat.link,
                        description:alldat.description,
                        guid:alldat.guid ,
                        catId:CON.utils.Global.api.currentPubid,
                        pubId:CON.utils.Global.api.currentCatid,
                        pubDate:alldat.pubDate
                    },

                    success: function(response) {
                        Ext.Viewport.setMasked(false);
                    },
                    failure: function(response) {
                        Ext.Viewport.setMasked(false);
                        //form.up('homepage').setActiveItem(1);
                    }
                });


        var newsDetailView = Ext.create('CON.view.publication.Detail',{});

        newsDetailView.setData(record.getData());

        CON.app.getController("Main").pushView(newsDetailView, CON.title);

    }

});