/*
 * File: app/view/publication/Detail.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CON.view.publication.Detail', {
    extend: 'Ext.Container',
    alias: 'widget.pubdetail',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        title: 'Cup of News',
        cls: 'con-bgcls',
        id: 'pubdetail',
        itemId: 'pubdetail',
        style: '-webkit-user-select:text !important;',
        scrollable: 'vertical',
        tpl: Ext.create('Ext.XTemplate', 
            '',
            '<div class="newsdetail-lastupdated" style="-webkit-user-select:text !important;">',
            '    <B style="',
            '    color: #FFFFFF;',
            '">Last updated : </B>{[this.getPubDateInHrs(values.pubDate)]}',
            '</div>',
            '<div class="newsdetail-title" style="-webkit-user-select:text !important;">{title}</div>',
            '<div class="newsdetail-description" id="newsdetail_description" style="-webkit-user-select:text !important;"> {[this.formatDesc(values.description)]}</div>',
            '',
            '<div style="clear:both;"></div>',
            '<div style="float:right;">',
            '    <div style="margin-right:48px;">',
            '    <img src="resources/project-images/google.png" class="shareGoogle"/>',
            '    </div>',
            '    ',
            '</div>',
            '<div style="float:right;">',
            '   ',
            '    <div style="margin-right:5px;">',
            '    <img src="resources/project-images/twitter.png" class="shareTwitter"/>',
            '    </div>',
            '    ',
            '</div>',
            '<div style="float:right;">',
            '    ',
            '    ',
            '    <div style="margin-right:5px;" >',
            '    <img src="resources/project-images/facebook.png" class="shareFacebook"/>',
            '    </div>',
            '</div>',
            '    ',
            '',
            '',
            '',
            {
                getPubDateInHrs: function(pubDate) {
                    var returnValue = '';
                    var newsPubDate;

                    if(pubDate.indexOf('0530') < 0){

                        newsPubDate = pubDate + '+0530';
                    }else{

                        newsPubDate = pubDate;
                    }


                    var hrs = (Math.abs((new Date()).valueOf() - new Date(newsPubDate).valueOf() )) / 1000/60/60;

                    if(!Ext.isEmpty(hrs)){

                        if(Math.round(hrs) < 24){
                            returnValue = Math.round(hrs) + ' hours ago';

                        }else{
                            returnValue = Math.round((hrs)/24) + ' days ago';

                        }
                    }else{

                        returnValue = '';
                    }

                    return returnValue;
                },
                formatDesc: function(desc) {

                    var touchdevice = ('ontouchstart' in window) ? true : false;
                    var app = document.URL.indexOf( 'http://' ) === -1 && document.URL.indexOf( 'https://' ) === -1;
                    var parser=new DOMParser();
                    var htmlDoc=parser.parseFromString(desc, "text/xml");
                    var newstr=desc;
                    var htmlDoc1=htmlDoc.getElementsByTagName('a');
                    var ancTag=htmlDoc1[0];
                    if(ancTag){
                        var hreftext=(ancTag.getAttribute('href'));
                        var returnDesc="";
                        if(app){
                            returnDesc='javascript:window.open("'+hreftext+'", "_blank", "location=no")';
                        }
                        else{
                            returnDesc='javascript:window.open("'+hreftext+'", "_blank")';

                        }

                        if(desc.indexOf(hreftext) > 0){
                            newstr=desc.replace(hreftext,returnDesc);
                        }

                    }else{

                    }




                    return newstr;


                }
            }
        ),
        listeners: [
            {
                fn: 'onContainerPainted',
                event: 'painted'
            }
        ]
    },

    onContainerPainted: function(element, eOpts) {



        /*
        element.dom.addEventListener('mouseup', function(e){
             Ext.Viewport.remove(panel);

                                                             if (window.getSelection) {

                    var val=(window.getSelection().toString());
                                                                 var text=(window.getSelection().toString());

                                                                                                                                                                    if (window.getSelection) {
                                                                                      if (window.getSelection().empty) {  // Chrome
                                                                                        window.getSelection().empty();
                                                                                      } else if (window.getSelection().removeAllRanges) {  // Firefox
                                                                                        window.getSelection().removeAllRanges();
                                                                                      }
                                                                                    } else if (document.selection) {  // IE?
                                                                                      document.selection.empty();
                                                                                    }
                                                                 if(val !== ""){
                                                                      Ext.Viewport.remove(panel);
                                                                     panel=Ext.create('Ext.Panel',{
                                                                       itemId:'floatingPanel',
                                                                       cls:'chartfloatingpanel-cls',
                                                                       top:e.y,
                                                                       left:e.x-100,
                                                                       width: 180,
                                                                       minHeight: 50,
                                                                         items:[
                                                                             {
                                                                                 xtype:"button",

                                                                                 text:"Add to Dictionary",
                                                                                 dock:"bottom",
                                                                                 handler : function(){

                                                                                     Ext.Viewport.remove(panel);
                                                                                    var DictonaryStore= Ext.getStore("Dictonary");
                                                                        var test= Ext.encode(Ext.getStore('Dictonary').getProxy().getReader().rawData);

                                                                         if(test === 'null'){
                                                                         var recordjson=[];

                                                                         var json={"id":new Date().getTime(),"word":text};
                                                                         recordjson.push(json);

                                                                          DictonaryStore.setData(recordjson);

                                                                                        window.localStorage.setItem("DictionaryArray",JSON.stringify(recordjson));


                                                                             }else{
                                                                                var recordjson=JSON.parse(test);
                                                                                  var json={"id":new Date().getTime(),"word":text};
                                                                         recordjson.push(json);

                                                                                 DictonaryStore.setData(recordjson);

                                                                                        window.localStorage.setItem("DictionaryArray",JSON.stringify(recordjson));


                                                                                      }






                                                                                 }

                                                                             }
                                                                         ]

                                                                   });
                                                                     panel.setHtml('<div style="text-align:justify;">'+val+'</div>');
                                                                   Ext.Viewport.add(panel);
                                                               }
                                                             }
                                                              });*/

        var facebookBtn = Ext.select('.shareFacebook').elements[0];
        var twitterBtn = Ext.select('.shareTwitter').elements[0];
        var googleBtn = Ext.select('.shareGoogle').elements[0];
        var touchdevice = ('ontouchstart' in window) ? true : false;
        var app = document.URL.indexOf( 'http://' ) === -1 && document.URL.indexOf( 'https://' ) === -1;


        var audioPlay=Ext.getCmp("audioPlay");
        audioPlay.setHidden(false);
        var shareText=this.getData().title;

        var node = document.getElementById('newsdetail_description'),

        htmlContent = node.innerHTML;
        var shareDesc=htmlContent;
        textContent = node.textContent;
        shareDesc=textContent;

        var url=Ext.getCmp("gotowebsiteBtn");

        var shareLink=url.siteUrl;
        Ext.get(facebookBtn).on('tap',function(e,a){
            //(new Media('http://translate.google.com/translate_tts?ie=UTF-8&tl=en&q=i%20have%20do%20this')).play();
            //var audio = new Audio();
            //audio.src='http://translate.google.com/translate_tts?ie=UTF-8&tl=en&q=elephant';
            //audio.play();
            if(app){
                 if(window.plugins.socialsharing){
                window.plugins.socialsharing.shareViaFacebook('', null /* img */,shareLink, function(res) {
                                                                        if(res == false){

                                                                        }else{

                                                                        }
                                                                        }, function(errormsg){});


                 }

            }else{
               window.open('https://www.facebook.com/sharer.php?' +
                'u=' + encodeURIComponent(shareLink) +
                '&t=' + encodeURIComponent(shareText));
            }


        });
        Ext.get(twitterBtn).on('tap',function(e,a){
             if(app){
                 if(window.plugins.socialsharing){
                 window.plugins.socialsharing.shareViaTwitter('', null /* img */,shareLink,function(res) {
                                                                       if(res == false){

                                                                       }else{

                                                                       }
                                                                       }, function(errormsg){
                                                                       //navigator.notification.alert(errormsg);
                                                                       });
               }
             }else{
                 window.open('https://twitter.com/intent/tweet?'+
                'original_referer=' + encodeURIComponent(shareLink) +
                '&url=' + encodeURIComponent(shareLink) +
                '&text=' + encodeURIComponent(shareText));
             }

           });
        Ext.get(googleBtn).on('tap',function(e,a){

             if(app){
                 if(window.plugins.socialsharing){
                 /*window.plugins.socialsharing.shareViaEmail(
                                                                     shareLink,
                                                                     'CON',
                                                                     null, // TO: must be null or an array
                                                                     null, // CC: must be null or an array
                                                                     null, // BCC: must be null or an array
                                                                     null,// FILES: can be null, a string, or an arra
                                                                     null, // called when sharing worked, but also when the user cancelled sharing via email (I've found no way to detect the difference)
                                                                     null // called when sh*t hits the fan
                                                                     );*/

                     var ref = window.open('https://plusone.google.com/_/+1/confirm?' +
                'url=' + encodeURIComponent(shareText), '_blank', 'location=no');
                     ref.addEventListener('loadstart', function(event) { if(((event.url).indexOf('https://plus.google.com/app/basic/stream')) >= 0){ref.close();} });


                }
             }else{
                 window.open('https://plusone.google.com/_/+1/confirm?' +
                'url=' + encodeURIComponent(shareText));
             }

           });

    },

    initialize: function() {
        this.callParent();

    },

    addToStore: function() {
        alert("ok");
    }

});