/*
 * File: app/view/HomeScreen.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CON.view.HomeScreen', {
    extend: 'Ext.Container',
    alias: 'widget.homescreen',

    requires: [
        'CON.view.category.ListCover',
        'CON.view.publication.List',
        'CON.view.Toprated',
        'Ext.Container',
        'Ext.Label',
        'Ext.Img'
    ],

    config: {
        cls: 'con-bgcls',
        itemId: 'HomeScreenLayout',
        layout: 'vbox',
        items: [
            {
                xtype: 'categorycover',
                centered: false,
                cls: 'coverplacecls',
                height: '50%'
            },
            {
                xtype: 'container',
                height: 300,
                layout: 'hbox',
                items: [
                    {
                        xtype: 'publicationlist',
                        'border-top': '2em',
                        centered: false,
                        height: '100%',
                        flex: 2
                    },
                    {
                        xtype: 'container',
                        flex: 1,
                        itemId: 'TopViewCont',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'label',
                                html: 'Favourites',
                                margin: '10 0 0 0',
                                style: 'color:#fff;'
                            },
                            {
                                xtype: 'container',
                                layout: 'fit',
                                items: [
                                    {
                                        xtype: 'image',
                                        height: 100,
                                        hidden: true,
                                        itemId: 'topViewed',
                                        margin: '4 40 40 40',
                                        padding: '',
                                        style: 'border-radius:14px;',
                                        width: 100,
                                        src: 'resources/project-images/topviewed.jpg'
                                    },
                                    {
                                        xtype: 'image',
                                        height: 100,
                                        hidden: true,
                                        margin: '4 40 40 40',
                                        padding: '',
                                        style: 'border-radius:14px;',
                                        width: 100,
                                        src: 'resources/project-images/img-rated.jpg'
                                    },
                                    {
                                        xtype: 'toprated',
                                        data: null,
                                        height: 300
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});