/*
 * File: app/view/MyDictionaryList.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CON.view.MyDictionaryList', {
    extend: 'Ext.Container',
    alias: 'widget.dictionarylist',

    requires: [
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        cls: 'con-bgcls',
        itemId: 'mydictionarycontent',
        layout: 'fit',
        items: [
            {
                xtype: 'list',
                cls: 'con-bgcls',
                height: '100%',
                id: 'dictionarylist',
                itemId: 'dictionarylist',
                itemTpl: Ext.create('Ext.XTemplate', 
                    '<div>',
                    '    <div>{word}</div>',
                    '    ',
                    '    <div style="float:right;margin-top: -26px;"><img src="resources/project-images/trash.png" style="height: 26px;width: 24px;margin-right: 38px;"  onClick=CON.app.deleteDictionary({id}); /></div>',
                    '    <!--',
                    '    <div style="float:right;margin-top: -29px;"><img src="resources/project-images/message-icon.png" style="height: 33px;',
                    'width: 37px;',
                    'margin-right: 8px;"/></div>-->',
                    '</div>',
                    '',
                    {
                        deleteDictionary: function(id) {
                            alert("ok");
                        }
                    }
                ),
                pressedCls: 'con-listitem-selectedcls',
                selectedCls: 'con-listitem-selectedcls',
                store: 'Dictonary',
                onItemDisclosure: true
            }
        ],
        listeners: [
            {
                fn: 'onMydictionarycontentPainted',
                event: 'painted'
            }
        ]
    },

    onMydictionarycontentPainted: function(element, eOpts) {


        /*var deleteButton = Ext.select('.deleteButton').elements[0];
         Ext.get(deleteButton).on('tap',function(e,a){
             alert("delete");

         });
        *//*
        var i=0;

        Ext.select('.deleteButton').each(function(el){
                el.on('tap',function(e,a){
             alert("delete");

         });


        });*/
    },

    deleteDictionary: function() {

    }

});