/*
 * File: app/view/MyMenu.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CON.view.MyMenu', {
    extend: 'Ext.Menu',

    requires: [
        'CON.view.PublicationPref',
        'Ext.Label',
        'Ext.form.Panel'
    ],

    config: {
        minWidth: '300px',
        width: '40%',
        items: [
            {
                xtype: 'label',
                html: 'User Preference',
                margin: '10 0 10 0',
                style: 'color:#FFF;text-align:center'
            },
            {
                xtype: 'publicationpref',
                height: '100%'
            }
        ]
    }

});