/*
 * File: app/view/PopUp.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CON.view.PopUp', {
    extend: 'Ext.Container',

    requires: [
        'Ext.Label',
        'Ext.Button'
    ],

    config: {
        cls: 'dict_pop',
        height: 120,
        width: 220,
        layout: {
            type: 'vbox',
            align: 'center',
            pack: 'center'
        },
        items: [
            {
                xtype: 'label',
                cls: 'dict_header-cls',
                html: '<div>Add Word</div><hr/>',
                margin: 'auto auto auto auto',
                width: '90%'
            },
            {
                xtype: 'label',
                html: 'Test Word',
                margin: 'auto auto auto auto',
                width: '90%'
            },
            {
                xtype: 'button',
                cls: 'add_dictionary',
                margin: '14 auto  auto  auto ',
                width: '90%',
                text: 'Add to Dictionary'
            }
        ]
    }

});