/*
 * File: app/view/Toprated.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CON.view.Toprated', {
    extend: 'Ext.Container',
    alias: 'widget.toprated',

    requires: [
        'Ext.dataview.DataView',
        'Ext.XTemplate'
    ],

    config: {
        cls: 'con-bgcls',
        id: 'publist2',
        itemId: 'publist',
        layout: 'fit',
        items: [
            {
                xtype: 'dataview',
                data: [
                    {
                        id: '1',
                        code: 'toi',
                        name: 'Times of India',
                        image: 'resources/project-images/topviewed.jpg',
                        active: '1'
                    },
                    {
                        id: '2',
                        code: 'et',
                        name: 'E Times',
                        image: 'resources/project-images/img-rated.jpg',
                        active: '1'
                    }
                ],
                itemId: 'mydataview3',
                padding: '',
                inline: true,
                itemTpl: [
                    '<img style="border-radius:14px;height:110px;width:113px;padding:10px;" src="{image}"/>'
                ]
            }
        ]
    }

});